[phases.setup]
nixPkgs = ["nodejs_20", "yt-dlp", "ffmpeg", "python311", "unzip"]

[phases.install]
cmds = [
  "npm install",
  "curl -fsSL https://deno.land/install.sh | sh",
  "cp /root/.deno/bin/deno /usr/local/bin/deno"
]

[start]
cmd = "node server.js"